### PR TITLE
add overloads for capturing data written to standard streams

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by ygel** [comment]
Look great, thanks! Seems like CI doesn't like stuff in stderr.
Question: what's the rationale behind `args` vs `windowsArgs`?

**Comment by adamralph** [comment]
Great, I'll need to sleep on it a little, to give my brain a chance to think of downsides.

Also, I'm a little worried about making SimpleExec less... "simple". I guess my main concern is keeping the API intuitive and simple.

Come to think of it, an alternative would be to keep `Read()` as is, and introduce a new `Capture()` (and `async` equivalent) for this purpose.

> what's the rationale behind `args` vs `windowsArgs`?

Please see https://github.com/adamralph/simple-exec/pull/128. Sometimes, the same command works on all platforms, e.g. `dotnet build`. Other times you need to do something different on Windows, e.g. https://github.com/adamralph/simple-exec/issues/119

**Comment by ygel** [comment]
In the keep it simple vein, introducing `RunWithProgress` (or something similar) which can notify with stdout/err data would work. It could report on newlines in the base case or, optionally, monitor `.BaseStream` if user desires so. Base case would work for majority of cases looking for line-by-line output and BaseStream monitoring would cover the rest, when command in question wants input and doesn't flush the stream or send a EOL.

**Comment by ygel** [comment]
> > what's the rationale behind `args` vs `windowsArgs`?
> Please see #128. Sometimes, the same command works on all platforms, e.g. `dotnet build`. Other times you need to do something different on Windows, e.g. #119

I see. I doubt that you still need to separate `process`/`windowsProcess` and `args`/`windowsArgs` anymore. With the current `CreateProcess` call `FileName` is your process name and `Arguments` are always arguments even on Windows:

```
FileName = "cmd.exe"
Arguments = "/c dir"
```
or
```
FileName = "notepad.exe"
Arguments = "<path_of_text_file>
```

**Comment by adamralph** [comment]
> In the keep it simple vein, introducing `RunWithProgress` (or something similar) which can notify with stdout/err data would work. It could report on newlines in the base case or, optionally, monitor `.BaseStream` if user desires so. Base case would work for majority of cases looking for line-by-line output and BaseStream monitoring would cover the rest, when command in question wants input and doesn't flush the stream or send a EOL.

@ygel I'm beginning to think that this belongs outside SimpleExec. Indeed, this is the very reason that I kept Bullseye and SimpleExec as two separate packages. That is, if SimpleExec doesn't provide what is required, then another package can be used instead which does. I created SimpleExec to do one very simple thing: to run a command, ignore the output, and use the exit code to determine whether it failed or not. The `Read()` method was [introduced in version 2.1.0](https://github.com/adamralph/simple-exec/issues/18) but I only use it myself in a couple of tests. Reading back over https://github.com/adamralph/simple-exec/issues/141, I believe what you need are several things which you can plug together, following the UNIX philosophy:

- start a process and get a handle to standard output and/or standard error
- pipe either of those streams through a `tee` equivalent which duplicates the stream into two streams
- pass one of the duplicate streams to something which will write to standard output or standard error
- pass the other duplicate stream to the next process, as its standard input

These things seems like great candidates to be provided by other packages, which effectively provide that *nix-like functionality at the .NET API level. As you say, even though this spike caters for the simple, line-terminating case, it breaks down when you consider standard input and the more general case which doesn't assume line termination.

**Comment by ygel** [comment]
No worries, I'll whip up something on my own.

**Pull request closed without merging**
