### PR TITLE
Added a command to capture standard output from a command.

### LINKED ISSUE #18: Create a method that can capture the output as a string.
```gitversion``` outputs json, I'd like to capture it as part of my build.

### PR DESCRIPTION
**Pull request by pauldotknopf**
Resolves #18

### CODE REVIEW

**Comment by adamralph** [comment]
BTW - sorry for the slow response. I've been away all week. 😃

**Comment by pauldotknopf** [comment]
I could have added some xUnit tests, but you are using xBehave, which I am not familiar with. I tried to following along, but it wasn't very intuitive or easy to pick up. Sorry.

**Comment by adamralph** [comment]
@pauldotknopf no problem, I actually had a bunch of tests ready to go for this exact feature in another branch. Even the name `Read()` matched. 😄 

Thanks again for the PR. I'll push out version 2.1.0 ASAP with this feature.

**Comment by pauldotknopf** [comment]
Thanks a lot!

**Pull request merged**
