### PR TITLE
FIxed issue with hanging on captures with large stdout.

### PR DESCRIPTION
**Pull request by pauldotknopf**
See #108

### CODE REVIEW

**Comment by pauldotknopf** [comment]
I have verified locally that my large stdout methods are now working.

**Comment by pauldotknopf** [comment]
I used the approach mentioned in blog post.

**Comment by thefringeninja** [comment]
I believe this is affecting me as well atm :(

**Comment by adamralph** [comment]
@pauldotknopf thanks again for raising this. I added a test and tweaked your changes in #111. I'll be releasing a new package shortly.

**Pull request closed without merging**
